/* tslint:disable */
// api v0.0.1 f9e089523144af8c4eeb52ad21ac6ad0e0bf2dca
// --
// This file has been generated by https://github.com/webrpc/webrpc using gen/typescript
// Do not edit by hand. Update your webrpc schema and re-generate.

// WebRPC description and code-gen version
export const WebRPCVersion = "v1"

// Schema version of your RIDL schema
export const WebRPCSchemaVersion = "v0.0.1"

// Schema hash generated from your RIDL schema
export const WebRPCSchemaHash = "f9e089523144af8c4eeb52ad21ac6ad0e0bf2dca"


//
// Types
//
export interface Status {
  success: boolean
  error: string
  id: number
  message: string
}

export interface AssetData {
  type: string
  file: string
}

export interface Asset {
  id?: number
  uuid?: string
  product_id: number
  resolution: string
  revision?: number
  data: AssetData
}

export interface AssetService {
  get(args: GetArgs, headers?: object): Promise<GetReturn>
  getAll(args: GetAllArgs, headers?: object): Promise<GetAllReturn>
  getByUUID(args: GetByUUIDArgs, headers?: object): Promise<GetByUUIDReturn>
}

export interface GetArgs {
  id: number
}

export interface GetReturn {
  result: Asset  
}
export interface GetAllArgs {
  product_id: number
  limit: number
}

export interface GetAllReturn {
  result: Array<Asset>  
}
export interface GetByUUIDArgs {
  uuid: string
}

export interface GetByUUIDReturn {
  result: Asset  
}


  
//
// Client
//
export class AssetService implements AssetService {
  private hostname: string
  private fetch: Fetch
  private path = '/rpc/AssetService/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname
    this.fetch = fetch
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  get = (args: GetArgs, headers?: object): Promise<GetReturn> => {
    return this.fetch(
      this.url('Get'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Asset>(_data.result)
        }
      })
    })
  }
  
  getAll = (args: GetAllArgs, headers?: object): Promise<GetAllReturn> => {
    return this.fetch(
      this.url('GetAll'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Array<Asset>>(_data.result)
        }
      })
    })
  }
  
  getByUUID = (args: GetByUUIDArgs, headers?: object): Promise<GetByUUIDReturn> => {
    return this.fetch(
      this.url('GetByUUID'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Asset>(_data.result)
        }
      })
    })
  }
  
}

  
export interface WebRPCError extends Error {
  code: string
  msg: string
	status: number
}

const createHTTPRequest = (body: object = {}, headers: object = {}): object => {
  return {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify(body || {})
  }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(err) {
      throw { code: 'unknown', msg: `expecting JSON, got: ${text}`, status: res.status } as WebRPCError
    }
    if (!res.ok) {
      throw data // webrpc error response
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>
