/* tslint:disable */
// api v0.0.1 143e460a1bd315c65968140fcf09c209c3f00aa0
// --
// This file has been generated by https://github.com/webrpc/webrpc using gen/typescript
// Do not edit by hand. Update your webrpc schema and re-generate.

// WebRPC description and code-gen version
export const WebRPCVersion = "v1"

// Schema version of your RIDL schema
export const WebRPCSchemaVersion = "v0.0.1"

// Schema hash generated from your RIDL schema
export const WebRPCSchemaHash = "143e460a1bd315c65968140fcf09c209c3f00aa0"


//
// Types
//
export interface Status {
  success: boolean
  error: string
  id: number
  message: string
}

export interface Company {
  id?: number
  name: string
  email: string
  address: string
  logo: string
}

export interface CompanyService {
  getCurrent(headers?: object): Promise<GetCurrentReturn>
}

export interface GetCurrentArgs {
}

export interface GetCurrentReturn {
  result: Company  
}


  
//
// Client
//
export class CompanyService implements CompanyService {
  private hostname: string
  private fetch: Fetch
  private path = '/rpc/CompanyService/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname
    this.fetch = fetch
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  getCurrent = (headers?: object): Promise<GetCurrentReturn> => {
    return this.fetch(
      this.url('GetCurrent'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Company>(_data.result)
        }
      })
    })
  }
  
}

  
export interface WebRPCError extends Error {
  code: string
  msg: string
	status: number
}

const createHTTPRequest = (body: object = {}, headers: object = {}): object => {
  return {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify(body || {})
  }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(err) {
      throw { code: 'unknown', msg: `expecting JSON, got: ${text}`, status: res.status } as WebRPCError
    }
    if (!res.ok) {
      throw data // webrpc error response
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>
