/* tslint:disable */
// api v0.0.1 f57fdf2d335776d3552126c9da1b330b7e60dd7a
// --
// This file has been generated by https://github.com/webrpc/webrpc using gen/typescript
// Do not edit by hand. Update your webrpc schema and re-generate.

// WebRPC description and code-gen version
export const WebRPCVersion = "v1"

// Schema version of your RIDL schema
export const WebRPCSchemaVersion = "v0.0.1"

// Schema hash generated from your RIDL schema
export const WebRPCSchemaHash = "f57fdf2d335776d3552126c9da1b330b7e60dd7a"


//
// Types
//
export interface Status {
  success: boolean
  error: string
  id: number
  message: string
}

export interface AssetData {
  type: string
  file: string
}

export interface Asset {
  id?: number
  uuid?: string
  product_id: number
  resolution: string
  revision?: number
  data: AssetData
}

export interface Coordinates {
  x: number
  y: number
  z: number
}

export interface Group {
  name: string
}

export interface Choice {
  name: string
  group?: number
  id: string
  thumbnail?: string
}

export interface Option {
  name: string
  groups?: Array<Group>
  choices: Array<Choice>
  id: string
}

export interface SizeOptions {
  step: number
  start: number
  end: number
}

export interface ProductData {
  size: Coordinates
  offset: Coordinates
  options?: Array<Option>
  size_options?: SizeOptions
  data_sheet?: string
}

export interface Product {
  id: number
  uuid?: string
  name: string
  description: string
  typ: string
  category: Category
  brand: Brand
  data: ProductData
  thumbnail: string
  price: number
  asset: Array<Asset>
}

export interface ProductRequest {
  id: number
  name: string
  description: string
  typ: string
  data: ProductData
  category_id: number
  brand_id: number
}

export interface Program {
  id?: number
  company_id: number
  name: string
  address: string
  thumbnail: string
  flat_count: number
  user_id: number
  products?: Array<number>
  data: string
}

export interface Brand {
  id: number
  name: string
}

export interface Category {
  id: number
  parent_id: number
  name: string
}

export interface AssetService {
  get(args: AssetServiceGetArgs, headers?: object): Promise<AssetServiceGetReturn>
  getAll(args: AssetServiceGetAllArgs, headers?: object): Promise<AssetServiceGetAllReturn>
  getByUUID(args: AssetServiceGetByUUIDArgs, headers?: object): Promise<AssetServiceGetByUUIDReturn>
}

export interface AssetServiceGetArgs {
  id: number
}

export interface AssetServiceGetReturn {
  result: Asset  
}
export interface AssetServiceGetAllArgs {
  product_id: number
  limit: number
}

export interface AssetServiceGetAllReturn {
  result: Array<Asset>  
}
export interface AssetServiceGetByUUIDArgs {
  uuid: string
}

export interface AssetServiceGetByUUIDReturn {
  result: Asset  
}

export interface ProductService {
  get(args: ProductServiceGetArgs, headers?: object): Promise<ProductServiceGetReturn>
  getAll(args: ProductServiceGetAllArgs, headers?: object): Promise<ProductServiceGetAllReturn>
  getByProgram(args: ProductServiceGetByProgramArgs, headers?: object): Promise<ProductServiceGetByProgramReturn>
  getBrands(headers?: object): Promise<ProductServiceGetBrandsReturn>
  getCategories(headers?: object): Promise<ProductServiceGetCategoriesReturn>
  getByCategory(args: ProductServiceGetByCategoryArgs, headers?: object): Promise<ProductServiceGetByCategoryReturn>
}

export interface ProductServiceGetArgs {
  id: number
}

export interface ProductServiceGetReturn {
  result: Product  
}
export interface ProductServiceGetAllArgs {
  typ: string
  limit: number
}

export interface ProductServiceGetAllReturn {
  result: Array<Product>  
}
export interface ProductServiceGetByProgramArgs {
  typ: string
  id: number
}

export interface ProductServiceGetByProgramReturn {
  result: Array<Product>  
}
export interface ProductServiceGetBrandsArgs {
}

export interface ProductServiceGetBrandsReturn {
  result: Array<Brand>  
}
export interface ProductServiceGetCategoriesArgs {
}

export interface ProductServiceGetCategoriesReturn {
  result: Array<Category>  
}
export interface ProductServiceGetByCategoryArgs {
  typ: string
  category: number
  limit: number
}

export interface ProductServiceGetByCategoryReturn {
  result: Array<Product>  
}


  
//
// Client
//
export class AssetService implements AssetService {
  private hostname: string
  private fetch: Fetch
  private path = '/rpc/AssetService/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname
    this.fetch = fetch
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  get = (args: AssetServiceGetArgs, headers?: object): Promise<AssetServiceGetReturn> => {
    return this.fetch(
      this.url('Get'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Asset>(_data.result)
        }
      })
    })
  }
  
  getAll = (args: AssetServiceGetAllArgs, headers?: object): Promise<AssetServiceGetAllReturn> => {
    return this.fetch(
      this.url('GetAll'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Array<Asset>>(_data.result)
        }
      })
    })
  }
  
  getByUUID = (args: AssetServiceGetByUUIDArgs, headers?: object): Promise<AssetServiceGetByUUIDReturn> => {
    return this.fetch(
      this.url('GetByUUID'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Asset>(_data.result)
        }
      })
    })
  }
  
}

export class ProductService implements ProductService {
  private hostname: string
  private fetch: Fetch
  private path = '/rpc/ProductService/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname
    this.fetch = fetch
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  get = (args: ProductServiceGetArgs, headers?: object): Promise<ProductServiceGetReturn> => {
    return this.fetch(
      this.url('Get'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Product>(_data.result)
        }
      })
    })
  }
  
  getAll = (args: ProductServiceGetAllArgs, headers?: object): Promise<ProductServiceGetAllReturn> => {
    return this.fetch(
      this.url('GetAll'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Array<Product>>(_data.result)
        }
      })
    })
  }
  
  getByProgram = (args: ProductServiceGetByProgramArgs, headers?: object): Promise<ProductServiceGetByProgramReturn> => {
    return this.fetch(
      this.url('GetByProgram'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Array<Product>>(_data.result)
        }
      })
    })
  }
  
  getBrands = (headers?: object): Promise<ProductServiceGetBrandsReturn> => {
    return this.fetch(
      this.url('GetBrands'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Array<Brand>>(_data.result)
        }
      })
    })
  }
  
  getCategories = (headers?: object): Promise<ProductServiceGetCategoriesReturn> => {
    return this.fetch(
      this.url('GetCategories'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Array<Category>>(_data.result)
        }
      })
    })
  }
  
  getByCategory = (args: ProductServiceGetByCategoryArgs, headers?: object): Promise<ProductServiceGetByCategoryReturn> => {
    return this.fetch(
      this.url('GetByCategory'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Array<Product>>(_data.result)
        }
      })
    })
  }
  
}

  
export interface WebRPCError extends Error {
  code: string
  msg: string
	status: number
}

const createHTTPRequest = (body: object = {}, headers: object = {}): object => {
  return {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify(body || {})
  }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(err) {
      throw { code: 'unknown', msg: `expecting JSON, got: ${text}`, status: res.status } as WebRPCError
    }
    if (!res.ok) {
      throw data // webrpc error response
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>
