/* tslint:disable */
// api v0.0.1 d7499ddac2d9c368aace4f770539fb5f70543034
// --
// This file has been generated by https://github.com/webrpc/webrpc using gen/typescript
// Do not edit by hand. Update your webrpc schema and re-generate.

// WebRPC description and code-gen version
export const WebRPCVersion = "v1"

// Schema version of your RIDL schema
export const WebRPCSchemaVersion = "v0.0.1"

// Schema hash generated from your RIDL schema
export const WebRPCSchemaHash = "d7499ddac2d9c368aace4f770539fb5f70543034"


//
// Types
//
export interface Status {
  success: boolean
  error: string
  id: number
  message: string
}

export interface Config {
  works_deadline: string
  coverings_deadline: string
  works_intro: string
  works_outro: string
  coverings_intro: string
  coverings_outro: string
  builder_intro: string
  builder_outro: string
}

export interface ProgramData {
  products: Array<ProductPrice>
  config: Config
}

export interface Picture {
  filename: string
  comment: string
}

export interface ProductPrice {
  id: number
  price: number
}

export interface Program {
  id?: number
  company_id: number
  name: string
  address: string
  thumbnail: string
  flat_count: number
  manager: number
  data: ProgramData
}

export interface ProgramService {
  get(args: GetArgs, headers?: object): Promise<GetReturn>
  getByCurrentCompany(headers?: object): Promise<GetByCurrentCompanyReturn>
  updateConfig(args: UpdateConfigArgs, headers?: object): Promise<UpdateConfigReturn>
  updateProductPrices(args: UpdateProductPricesArgs, headers?: object): Promise<UpdateProductPricesReturn>
}

export interface GetArgs {
  id: number
}

export interface GetReturn {
  result: Program  
}
export interface GetByCurrentCompanyArgs {
}

export interface GetByCurrentCompanyReturn {
  result: Array<Program>  
}
export interface UpdateConfigArgs {
  id: number
  config: Config
}

export interface UpdateConfigReturn {
  status: Status  
}
export interface UpdateProductPricesArgs {
  id: number
  prices: Array<ProductPrice>
}

export interface UpdateProductPricesReturn {
  status: Status  
}


  
//
// Client
//
export class ProgramService implements ProgramService {
  private hostname: string
  private fetch: Fetch
  private path = '/rpc/ProgramService/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname
    this.fetch = fetch
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  get = (args: GetArgs, headers?: object): Promise<GetReturn> => {
    return this.fetch(
      this.url('Get'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Program>(_data.result)
        }
      })
    })
  }
  
  getByCurrentCompany = (headers?: object): Promise<GetByCurrentCompanyReturn> => {
    return this.fetch(
      this.url('GetByCurrentCompany'),
      createHTTPRequest({}, headers)
      ).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Array<Program>>(_data.result)
        }
      })
    })
  }
  
  updateConfig = (args: UpdateConfigArgs, headers?: object): Promise<UpdateConfigReturn> => {
    return this.fetch(
      this.url('UpdateConfig'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <Status>(_data.status)
        }
      })
    })
  }
  
  updateProductPrices = (args: UpdateProductPricesArgs, headers?: object): Promise<UpdateProductPricesReturn> => {
    return this.fetch(
      this.url('UpdateProductPrices'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <Status>(_data.status)
        }
      })
    })
  }
  
}

  
export interface WebRPCError extends Error {
  code: string
  msg: string
	status: number
}

const createHTTPRequest = (body: object = {}, headers: object = {}): object => {
  return {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify(body || {})
  }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(err) {
      throw { code: 'unknown', msg: `expecting JSON, got: ${text}`, status: res.status } as WebRPCError
    }
    if (!res.ok) {
      throw data // webrpc error response
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>
