/* tslint:disable */
// api v0.0.1 f6b9d7aa319e7d651e7d223d89593544919970f0
// --
// This file has been generated by https://github.com/webrpc/webrpc using gen/typescript
// Do not edit by hand. Update your webrpc schema and re-generate.

// WebRPC description and code-gen version
export const WebRPCVersion = "v1"

// Schema version of your RIDL schema
export const WebRPCSchemaVersion = "v0.0.1"

// Schema hash generated from your RIDL schema
export const WebRPCSchemaHash = "f6b9d7aa319e7d651e7d223d89593544919970f0"


//
// Types
//
export interface Status {
  success: boolean
  error: string
  id: number
  message: string
}

export interface Quote {
  id?: number
  uuid?: string
  title: string
  program_id: number
  floorplan_id?: number
  logo?: string
  description?: string
  data: {[key: string]: any}
  status: {[key: string]: any}
  number: number
}

export interface QuoteService {
  get(args: GetArgs, headers?: object): Promise<GetReturn>
  getByUUID(args: GetByUUIDArgs, headers?: object): Promise<GetByUUIDReturn>
}

export interface GetArgs {
  id: number
}

export interface GetReturn {
  result: Quote  
}
export interface GetByUUIDArgs {
  uuid: string
}

export interface GetByUUIDReturn {
  result: Quote  
}


  
//
// Client
//
export class QuoteService implements QuoteService {
  private hostname: string
  private fetch: Fetch
  private path = '/rpc/QuoteService/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname
    this.fetch = fetch
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  get = (args: GetArgs, headers?: object): Promise<GetReturn> => {
    return this.fetch(
      this.url('Get'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Quote>(_data.result)
        }
      })
    })
  }
  
  getByUUID = (args: GetByUUIDArgs, headers?: object): Promise<GetByUUIDReturn> => {
    return this.fetch(
      this.url('GetByUUID'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Quote>(_data.result)
        }
      })
    })
  }
  
}

  
export interface WebRPCError extends Error {
  code: string
  msg: string
	status: number
}

const createHTTPRequest = (body: object = {}, headers: object = {}): object => {
  return {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify(body || {})
  }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(err) {
      throw { code: 'unknown', msg: `expecting JSON, got: ${text}`, status: res.status } as WebRPCError
    }
    if (!res.ok) {
      throw data // webrpc error response
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>
