/* tslint:disable */
// api v0.0.1 4b9b8b5953d9ac3bfb38e5fef75ced277d6592b1
// --
// This file has been generated by https://github.com/webrpc/webrpc using gen/typescript
// Do not edit by hand. Update your webrpc schema and re-generate.

// WebRPC description and code-gen version
export const WebRPCVersion = "v1"

// Schema version of your RIDL schema
export const WebRPCSchemaVersion = "v0.0.1"

// Schema hash generated from your RIDL schema
export const WebRPCSchemaHash = "4b9b8b5953d9ac3bfb38e5fef75ced277d6592b1"


//
// Types
//
export interface Status {
  success: boolean
  error: string
  id: number
  message: string
}

export interface Buyer {
  name: string
  email: string
}

export interface SectorData {
  buyer: Buyer
}

export interface Quote {
  id?: number
  title: string
  program_id: number
  floorplan_id?: number
  logo?: string
  description?: string
  data: {[key: string]: any}
  status: {[key: string]: any}
}

export interface Sector {
  id?: number
  uuid: string
  company_id: number
  program_id: number
  user_id: number
  name: string
  floor_no: number
  data?: SectorData
  floorplan?: Floorplan
  owner_name?: string
  owner_email?: string
  original_bf_id: number
}

export interface Floorplan {
  id: number
  sector_id: number
  name: string
  image: string
  data: {[key: string]: any}
  status?: {[key: string]: any}
  version: number
  quotes?: Array<Quote>
}

export interface SectorService {
  get(args: GetArgs, headers?: object): Promise<GetReturn>
  getByProgram(args: GetByProgramArgs, headers?: object): Promise<GetByProgramReturn>
  assignBuyer(args: AssignBuyerArgs, headers?: object): Promise<AssignBuyerReturn>
  getByUUID(args: GetByUUIDArgs, headers?: object): Promise<GetByUUIDReturn>
}

export interface GetArgs {
  id: number
}

export interface GetReturn {
  result: Sector  
}
export interface GetByProgramArgs {
  program_id: number
}

export interface GetByProgramReturn {
  result: Array<Sector>  
}
export interface AssignBuyerArgs {
  id: number
  user_id: number
}

export interface AssignBuyerReturn {
  status: Status  
}
export interface GetByUUIDArgs {
  uuid: string
}

export interface GetByUUIDReturn {
  result: Sector  
}


  
//
// Client
//
export class SectorService implements SectorService {
  private hostname: string
  private fetch: Fetch
  private path = '/rpc/SectorService/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname
    this.fetch = fetch
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  get = (args: GetArgs, headers?: object): Promise<GetReturn> => {
    return this.fetch(
      this.url('Get'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Sector>(_data.result)
        }
      })
    })
  }
  
  getByProgram = (args: GetByProgramArgs, headers?: object): Promise<GetByProgramReturn> => {
    return this.fetch(
      this.url('GetByProgram'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Array<Sector>>(_data.result)
        }
      })
    })
  }
  
  assignBuyer = (args: AssignBuyerArgs, headers?: object): Promise<AssignBuyerReturn> => {
    return this.fetch(
      this.url('AssignBuyer'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          status: <Status>(_data.status)
        }
      })
    })
  }
  
  getByUUID = (args: GetByUUIDArgs, headers?: object): Promise<GetByUUIDReturn> => {
    return this.fetch(
      this.url('GetByUUID'),
      createHTTPRequest(args, headers)).then((res) => {
      return buildResponse(res).then(_data => {
        return {
          result: <Sector>(_data.result)
        }
      })
    })
  }
  
}

  
export interface WebRPCError extends Error {
  code: string
  msg: string
	status: number
}

const createHTTPRequest = (body: object = {}, headers: object = {}): object => {
  return {
    method: 'POST',
    headers: { ...headers, 'Content-Type': 'application/json' },
    body: JSON.stringify(body || {})
  }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(err) {
      throw { code: 'unknown', msg: `expecting JSON, got: ${text}`, status: res.status } as WebRPCError
    }
    if (!res.ok) {
      throw data // webrpc error response
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>
